var images = [
    {
        "filename": "tooltip.png",
        "title": "Jelly G. on tooltips overflowing",
        "author": "Vex",
        "date": "08 Apr 2024 00:38:00 GMT",
        "comment": "Jelly G.'s first appearance!",
    },
    {
        "filename": "failed.png",
        "title": "Failed",
        "author": "Vex",
        "date": "08 Apr 2024 06:12:00 GMT",
        "comment": "",
    },
    {
        "filename": "makestatequivalent.png",
        "title": "Jelly G. on makeStatEquivalent()",
        "author": "Vex",
        "date": "09 Apr 2024 01:34:00 GMT",
        "comment": "",
    },
    {
        "filename": "done.png",
        "title": "Done",
        "author": "Vex",
        "date": "09 Apr 2024 01:38:00 GMT",
        "comment": "",
    },
    {
        "filename": "evening.png",
        "title": "Evening",
        "author": "Vex",
        "date": "09 Apr 2024 01:57:00 GMT",
        "comment": "",
    },
    {
        "filename": "elevators.png",
        "title": "Jelly G. on elevators",
        "author": "Vex",
        "date": "09 Apr 2024 03:24:00 GMT",
        "comment": "",
    },
    {
        "filename": "overloads.png",
        "title": "Jelly G. on patching with overloads",
        "author": "Vex",
        "date": "09 Apr 2024 04:56:00 GMT",
        "comment": "",
    },
    {
        "filename": "sleep.png",
        "title": "Bed",
        "author": "Vex",
        "date": "09 Apr 2024 05:01:00 GMT",
        "comment": "",
    },
    {
        "filename": "topup.png",
        "title": "Top-up tokens",
        "author": "ocean",
        "date": "09 Apr 2024 05:04:00 GMT",
        "comment": "",
    },
    {
        "filename": "typing.png",
        "title": "Jelly G. on... typing?",
        "author": "Vex",
        "date": "10 Apr 2024 19:25:00 GMT",
        "comment": "",
    },
    {
        "filename": "starburst.png",
        "title": "time for my first attack.. STAR BURST GO!!!",
        "author": "Vex",
        "date": "11 Apr 2024 02:41:00 GMT",
        "comment": "",
    },
    {
        "filename": "defence.png",
        "title": "star burst defence",
        "author": "ocean",
        "date": "11 Apr 2024 02:43:00 GMT",
        "comment": "",
    },
    {
        "filename": "charging.png",
        "title": "Charging up",
        "author": "Vex",
        "date": "11 Apr 2024 02:46:00 GMT",
        "comment": "",
    },
    {
        "filename": "death.png",
        "title": "Jelly G. dies",
        "author": "ocean",
        "date": "11 Apr 2024 02:50:00 GMT",
        "comment": "",
    },
    {
        "filename": "aftermath.png",
        "title": "Jelly G.'s dead.",
        "author": "Vex",
        "date": "11 Apr 2024 02:55:00 GMT",
        "comment": "",
    },
    {
        "filename": "ondeath.png",
        "title": "Jelly H. on death",
        "author": "ocean",
        "date": "11 Apr 2024 02:59:00 GMT",
        "comment": "",
    },
    {
        "filename": "trianglebayonets.png",
        "title": "Jelly G. on triangle bayonets",
        "author": "Vex",
        "date": "13 Apr 2024 07:59:00 GMT",
        "comment": "",
    },
    {
        "filename": "jigsaw.png",
        "title": "Jelly G. gets it",
        "author": "ocean",
        "date": "24 Apr 2024 19:54:00 GMT",
        "comment": "",
    },
    {
        "filename": "super.png",
        "title": "Super G.",
        "author": "ocean",
        "date": "29 Apr 2024 20:41:00 GMT",
        "comment": "",
    },
    {
        "filename": "speecH.png",
        "title": "\"really skeptical of this \'Super G.\' guy, how come we've never seen them and liz truss in the same room?\"",
        "author": "ocean",
        "date": "29 Apr 2024 20:44:00 GMT",
        "comment": "",
    },
    {
        "filename": "sockets.png",
        "title": "Eyesockets",
        "author": "ocean",
        "date": "30 Apr 2024 20:49:00 GMT",
        "comment": "",
    },
    {
        "filename": "flibbleblop.png",
        "title": "Flibbleblop Book Signing",
        "author": "Vex",
        "date": "30 Apr 2024 20:54:00 GMT",
        "comment": "",
    },
    {
        "filename": "blueprint.png",
        "title": "Fortnite dystopia blueprint",
        "author": "Vex",
        "date": "03 May 2024 20:42:00 GMT",
        "comment": "\"i actually do think everyone should play fortnite, like in my utopia your bed retracts into the wall and extends, and it only extends if you play 3 rounds of fortnite a day, so otherwise you have to sleep on the floor\"",
    },
    {
        "filename": "epic.png",
        "title": "Jelly G. forgets his Epic Games login",
        "author": "Vex",
        "date": "03 May 2024 20:51:00 GMT",
        "comment": "",
    },
    {
        "filename": "approved.png",
        "title": "Approved",
        "author": "ocean",
        "date": "26 May 2024 21:55:00 GMT",
        "comment": "",
    },
    {
        "filename": "oneoff.png",
        "title": "Just a one-off",
        "author": "Vex",
        "date": "04 Jun 2024 02:39:00 GMT",
        "comment": "",
    },
    {
        "filename": "fimble.png",
        "title": "Noxious Fimble captures Jelly G.",
        "author": "ocean",
        "date": "04 Jun 2024 02:51:00 GMT",
        "comment": "",
    },
    {
        "filename": "jail.png",
        "title": "Jail",
        "author": "ocean",
        "date": "05 Jun 2024 03:13:00 GMT",
        "comment": "",
    },
    {
        "filename": "Happeares.png",
        "title": "Jelly H. appears!",
        "author": "Vex",
        "date": "05 Jun 2024 06:15:00 GMT",
        "comment": "",
    },
    {
        "filename": "recommend.png",
        "title": "Jelly G. recommends Jelly G. for the job",
        "author": "ocean",
        "date": "08 Jun 2024 07:49:00 GMT",
        "comment": "",
    },
    {
        "filename": "debugger.png",
        "title": "Debugger",
        "author": "ocean",
        "date": "15 Jun 2024 15:04:00 GMT",
        "comment": "",
    },
    {
        "filename": "debuddy.png",
        "title": "De buddy",
        "author": "ocean",
        "date": "15 Jun 2024 15:16:00 GMT",
        "comment": "",
    },
    {
        "filename": "pet.png",
        "title": "Jelly G.'s pet: stone fricking thing",
        "author": "Vex",
        "date": "15 Jun 2024 23:28:00 GMT",
        "comment": "",
    },
    {
        "filename": "inspect.png",
        "title": "Accessorising",
        "author": "ocean",
        "date": "18 Jun 2024 00:01:00 GMT",
        "comment": "",
    },
    {
        "filename": "doodle.png",
        "title": "Jelly Doodles",
        "author": "ocean",
        "date": "06 Jul 2025 05:28:00 GMT",
        "comment": "",
    },
    {
        "filename": "bugs.png",
        "title": "\"On the bright side I got most of my bugs worked out before they called me\"",
        "author": "ocean",
        "date": "27 Jul 2024 20:45:00 GMT",
        "comment": "",
    },
    {
        "filename": "mouse.png",
        "title": "Jelly G. gets a new mouse",
        "author": "Enbeon",
        "date": "27 Jul 2024 20:54:00 GMT",
        "comment": "",
    },
    {
        "filename": "fridge.png",
        "title": "Fridge G.",
        "author": "ocean",
        "date": "27 Jul 2024 21:03:00 GMT",
        "comment": "these captchas are getting difficult help??",
    },
    {
        "filename": "cold.png",
        "title": "Jelly G. freezes over",
        "author": "Vex",
        "date": "27 Jul 2024 21:06:00 GMT",
        "comment": "",
    },
    {
        "filename": "assist.png",
        "title": "assist",
        "author": "Vex",
        "date": "27 Jul 2024 21:26:00 GMT",
        "comment": "",
    },
    {
        "filename": "londoneye.png",
        "title": "The London Eye",
        "author": "ocean",
        "date": "28 Jul 2024 21:33:00 GMT",
        "comment": "",
    },
    {
        "filename": "escape.png",
        "title": "Escape",
        "author": "Vex",
        "date": "28 Jul 2024 21:34:00 GMT",
        "comment": "",
    },
    {
        "filename": "booking.png",
        "title": "Jelly G. books a trip to see the London Eye",
        "author": "Vex",
        "date": "28 Jul 2024 21:42:00 GMT",
        "comment": "",
    },
    {
        "filename": "eviction.png",
        "title": "Jelly G. plays opens a blind box type thing (Kuji)",
        "author": "ocean",
        "date": "28 Jul 2024 21:58:00 GMT",
        "comment": "",
    },
    {
        "filename": "fimblebox.png",
        "title": "Noxious Fimble plays opens a blind box type thing (Kuji)",
        "author": "Vex",
        "date": "28 Jul 2024 22:13:00 GMT",
        "comment": "",
    },
    {
        "filename": "entity.png",
        "title": "Another CAPTCHA",
        "author": "Enbeon",
        "date": "28 Jul 2024 22:20:00 GMT",
        "comment": "",
    },
    {
        "filename": "amogus.png",
        "title": "Amogus",
        "author": "Enbeon",
        "date": "01 Aug 2024 17:51:00 GMT",
        "comment": "",
    },
    {
        "filename": "work.png",
        "title": "Jelly H. leaves for work",
        "author": "Vex",
        "date": "03 Aug 2024 15:35:00 GMT",
        "comment": "",
    },
    {
        "filename": "platform.png",
        "title": "\"he forgot you need to have a good platform for people to want to advertise on it\"",
        "author": "ocean",
        "date": "19 Aug 2024 18:55:00 GMT",
        "comment": "",
    },
    {
        "filename": "drawin.png",
        "title": "Drawin G.",
        "author": "ocean",
        "date": "19 Aug 2024 21:09:00 GMT",
        "comment": "",
    },
    {
        "filename": "toys.png",
        "title": "Window Shopping",
        "author": "ocean",
        "date": "04 Sep 2024 23:06:00 GMT",
        "comment": "",
    },
    {
        "filename": "summon.png",
        "title": "Jelly G. summons two thirds of a demon",
        "author": "Vex",
        "date": "06 Sep 2024 19:08:00 GMT",
        "comment": "",
    },
    {
        "filename": "borp.png",
        "title": "An unfinished Jelly G.",
        "author": "Vex",
        "date": "18 Aug 2024 11:40:00 GMT",
        "comment": "",
    },
    {
        "filename": "test.png",
        "title": "Jelly G. takes a test",
        "author": "ocean",
        "date": "30 Sep 2024 21:34:00 GMT",
        "comment": "",
    },
    {
        "filename": "coffee.png",
        "title": "DWINK COFFEEE",
        "author": "Vex",
        "date": "04 Oct 2024 01:30:00 GMT",
        "comment": "",
    },
    {
        "filename": "praise.png",
        "title": "Praise",
        "author": "ocean",
        "date": "05 Oct 2024 16:04:00 GMT",
        "comment": "",
    },
    {
        "filename": "lift.png",
        "title": "Jelly G. even lifts",
        "author": "Vex",
        "date": "06 Oct 2024 21:49:00 GMT",
        "comment": "",
    },
    {
        "filename": "feather.png",
        "title": "Feather",
        "author": "Vex",
        "date": "06 Oct 2024 21:59:00 GMT",
        "comment": "",
    },
    {
        "filename": "sortedcarton.png",
        "title": "Murder Mystery",
        "author": "Vex",
        "date": "07 Oct 2024 18:30:00 GMT",
        "comment": "",
    },
    {
        "filename": "interrogation.png",
        "title": "Interrogation",
        "author": "ocean",
        "date": "07 Oct 2024 18:50:00 GMT",
        "comment": "",
    },
    {
        "filename": "confession.png",
        "title": "Confession",
        "author": "Vex",
        "date": "07 Oct 2024 18:51:00 GMT",
        "comment": "",
    },
    {
        "filename": "unsorted.png",
        "title": "Unsorted Carton arrives late",
        "author": "ocean",
        "date": "07 Oct 2024 19:06:00 GMT",
        "comment": "",
    },
    {
        "filename": "porpol.png",
        "title": "Interrogation 2",
        "author": "Vex",
        "date": "07 Oct 2024 19:22:00 GMT",
        "comment": "",
    },
    {
        "filename": "accusation.png",
        "title": "Accusation",
        "author": "ocean",
        "date": "07 Oct 2024 19:38:00 GMT",
        "comment": "",
    },
    {
        "filename": "bulby.png",
        "title": "Light Bulby is accused",
        "author": "ocean",
        "date": "07 Oct 2024 19:57:00 GMT",
        "comment": "",
    },
    {
        "filename": "flashback.png",
        "title": "Flashback",
        "author": "Vex",
        "date": "07 Oct 2024 21:59:00 GMT",
        "comment": "",
    },
    {
        "filename": "train.png",
        "title": "The Train",
        "author": "Vex",
        "date": "09 Oct 2024 00:48:00 GMT",
        "comment": "",
    },
    {
        "filename": "subconscious.png",
        "title": "Subconscious",
        "author": "Vex",
        "date": "09 Oct 2024 01:16:00 GMT",
        "comment": "",
    },
    {
        "filename": "puns.png",
        "title": "Puns",
        "author": "Vex",
        "date": "09 Oct 2024 01:21:00 GMT",
        "comment": "",
    },
    {
        "filename": "bulbyslander.png",
        "title": "\"honestly fuck you sorted carton youll never  be good enough to be my fourth best friend\"",
        "author": "Vex",
        "date": "14 Oct 2024 19:12:00 GMT",
        "comment": "",
    },
    {
        "filename": "circus.png",
        "title": "Jelly G. works in the circus",
        "author": "Vex",
        "date": "17 Oct 2024 22:24:00 GMT",
        "comment": "",
    },
    {
        "filename": "boiler.png",
        "title": "Jelly G. gets taken to the boiler room",
        "author": "ocean",
        "date": "31 Oct 2024 19:35:00 GMT",
        "comment": "",
    },
    {
        "filename": "belong.png",
        "title": "A Mistake",
        "author": "Vex",
        "date": "31 Oct 2024 19:49:00 GMT",
        "comment": "",
    },
    {
        "filename": "minesweep.png",
        "title": "Help",
        "author": "Enbeon",
        "date": "21 Nov 2024 01:05:00 GMT",
        "comment": "",
    },
    {
        "filename": "hanukkah.png",
        "title": "Jelly G. forgot presents!!",
        "author": "Vex",
        "date": "21 Dec 2024 02:57:00 GMT",
        "comment": "",
    },
    {
        "filename": "lowtierfriend.png",
        "title": "Low Tier Friend",
        "author": "Vex",
        "date": "21 Dec 2024 03:03:00 GMT",
        "comment": "",
    },
    {
        "filename": "prisonrealm.png",
        "title": "Meanwhile, in the prison realm...",
        "author": "Vex",
        "date": "21 Dec 2024 04:01:00 GMT",
        "comment": "",
    },
    {
        "filename": "chees.png",
        "title": "CHEES",
        "author": "Vex",
        "date": "21 Dec 2024 23:02:00 GMT",
        "comment": "",
    },
    {
        "filename": "gellyj1.png",
        "title": "just drew a fucked up and evil version of jelly G... just a sicked and twisted look into my mind..",
        "author": "Enbeon",
        "date": "29 Dec 2024 21:54:00 GMT",
        "comment": "",
    },
    {
        "filename": "gellyj.png",
        "title": "Gelly J.",
        "author": "Vex",
        "date": "29 Dec 2024 21:59:00 GMT",
        "comment": "",
    },
    {
        "filename": "hostage.png",
        "title": "Jelly G. gets stuck in a hostage situation",
        "author": "Vex",
        "date": "30 Dec 2024 19:02:00 GMT",
        "comment": "",
    },
    {
        "filename": "collateral.png",
        "title": "\"is that all i am to you?? collateral??\"",
        "author": "ocean",
        "date": "30 Dec 2024 19:04:00 GMT",
        "comment": "",
    },
    {
        "filename": "afraid.png",
        "title": "Jelly G. is gonna die",
        "author": "Vex",
        "date": "30 Dec 2024 19:10:00 GMT",
        "comment": "",
    },
    {
        "filename": "memoriam.png",
        "title": "In Memoriam",
        "author": "Vex",
        "date": "30 Dec 2024 19:13:00 GMT",
        "comment": "",
    },
    {
        "filename": "kill.png",
        "title": "It's time...",
        "author": "Vex",
        "date": "31 Dec 2024 19:06:00 GMT",
        "comment": "",
    },
    {
        "filename": "onemorething.png",
        "title": "One More Thing...",
        "author": "Vex",
        "date": "31 Dec 2024 19:09:00 GMT",
        "comment": "",
    },
    {
        "filename": "gellyjreturns.png",
        "title": "Gelly J. Returns",
        "author": "Vex",
        "date": "31 Dec 2024 19:15:00 GMT",
        "comment": "",
    },
    {
        "filename": "jellybux.png",
        "title": "$100,00 in jelly g.bucks",
        "author": "Vex",
        "date": "02 Jan 2025 00:57:00 GMT",
        "comment": "",
    },
    {
        "filename": "oversent.png",
        "title": "holy crap!!! that's $100,000 i said $100,00!!!",
        "author": "Vex",
        "date": "02 Jan 2025 01:00:00 GMT",
        "comment": "",
    },
    {
        "filename": "nightmare.png",
        "title": "Nightmare",
        "author": "Vex",
        "date": "05 Jan 2025 18:09:00 GMT",
        "comment": "",
    },
    {
        "filename": "doubled.png",
        "title": "Double it and give it to the next person",
        "author": "ocean",
        "date": "26 Feb 2025 18:19:00 GMT",
        "comment": "",
    },
    {
        "filename": "sigma.png",
        "title": "what the sigma",
        "author": "Vex",
        "date": "27 Feb 2025 20:57:00 GMT",
        "comment": "",
    },
    {
        "filename": "tinyg.png",
        "title": "Tiny G.",
        "author": "Vex",
        "date": "05 Mar 2025 01:16:00 GMT",
        "comment": "",
    },
    {
        "filename": "wish.png",
        "title": "Fairy G.",
        "author": "ocean",
        "date": "09 Mar 2025 03:37:00 GMT",
        "comment": "",
    },
    {
        "filename": "hat1.png",
        "title": "If Jelly G. wore (a) hat(s) would he wear it/them like this...",
        "author": "ocean",
        "date": "09 Mar 2025 16:58:00 GMT",
        "comment": "",
    },
    {
        "filename": "hat2.png",
        "title": "...or like this?",
        "author": "ocean",
        "date": "09 Mar 2025 17:12:00 GMT",
        "comment": "",
    },
	{
		"filename": "customhat.png",
		"title": "Another Option",
		"author": "Ardent",
		"date": "09 Mar 2025 18:32:00 GMT",
		"comment": "",
	},
    {
        "filename": "sunset.png",
        "title": "Sunrise",
        "author": "Vex",
        "date": "09 Mar 2025 17:17:00 GMT",
        "comment": "",
    },
    {
        "filename": "jellypedia.png",
        "title": "The Jellypedia Forms",
        "author": "Vex",
        "date": "09 Mar 2025 20:21:00 GMT",
        "comment": "",
    },
    {
        "filename": "turing.png",
        "title": "Jelly G. thanks his distant relative",
        "author": "Vex",
        "date": "09 Mar 2025 22:47:00 GMT",
        "comment": "",
    },
    {
        "filename": "rodrick.png",
        "title": "Jelly G. reads diary of a wimpy kid: rodrick rules",
        "author": "ocean",
        "date": "10 Mar 2025 22:20:00 GMT",
        "comment": "",
    },
    {
        "filename": "manny.png",
        "title": "Manny is ownwy thwee",
        "author": "ocean",
        "date": "10 Mar 2025 22:44:00 GMT",
        "comment": "",
    },
    {
        "filename": "adventure.png",
        "title": "jelly adventure",
        "author": "Vex",
        "date": "13 Mar 2025 20:39:00 GMT",
        "comment": "",
    },
    {
        "filename": "gathering.png",
        "title": "this magic game is confusing",
        "author": "ocean",
        "date": "20 Mar 2025 17:37:00 GMT",
        "comment": "",
    },
    {
        "filename": "gumballguy.png",
        "title": "jelly g in my notes app is lazy but gumball guy from regular show wants him to get back to work because that's what that guy said on regular sjow!!!",
        "author": "Vex",
        "date": "20 Mar 2025 17:42:00 GMT",
        "comment": "",
    },
    {
        "filename": "slackoff.png",
        "title": "Jelly G. slacks off",
        "author": "Autumn",
        "date": "20 Mar 2025 17:55:00 GMT",
        "comment": "",
    },
    {
        "filename": "birthday.png",
        "title": "Jelly G. can't wait for his birthday",
        "author": "ocean",
        "date": "20 Mar 2025 18:14:00 GMT",
        "comment": "",
    },
    {
        "filename": "cinema.png",
        "title": "Absolute Cinema",
        "author": "Enbeon",
        "date": "23 Mar 2025 21:16:00 GMT",
        "comment": "",
    },
    {
        "filename": "crucifixion.png",
        "title": "Jelly G. gets crucified",
        "author": "occultpyromancer",
        "date": "23 Mar 2025 21:42:00 GMT",
        "comment": "",
    },
    {
        "filename": "jellybirthday.png",
        "title": "Jelly G.'s first surprise birthday party",
        "author": "ocean",
        "date": "07 Apr 2025 18:46:00 GMT",
        "comment": "",
    },
    {
        "filename": "pepsithing.png",
        "title": "\"Pepsi spent millions of dollars to design a new logo that could function in outer space... Coca-Cola used a pencil.\"",
        "author": "anon",
        "date": "07 Apr 2025 21:47:00 GMT",
        "comment": "90% of this image is credit to Randall Munroe",
    },
    {
        "filename": "vexart.png",
        "title": "i like vex art",
        "author": "ocean",
        "date": "10 Apr 2025 17:26:00 GMT",
        "comment": "",
    },
    {
        "filename": "vacation.png",
        "title": "Jelly G. needs a vacation",
        "author": "Vex",
        "date": "10 Apr 2025 17:48:00 GMT",
        "comment": "",
    },
    {
        "filename": "welcometohell.png",
        "title": "Jelly G.'s vacation doesn't go to plan",
        "author": "Vex",
        "date": "11 Apr 2025 02:59:00 GMT",
        "comment": "",
    },
    {
        "filename": "resurrection.png",
        "title": "\"Mother of Resurrection\"",
        "author": "Lua Viper",
        "date": "16 Apr 2025 20:02:00 GMT",
        "comment": "",
    },
    {
        "filename": "help.png",
        "title": "Jelly G. on getting help",
        "author": "Vex",
        "date": "24 Apr 2025 02:11:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "quicklydrawn.png",
        "title": "extremely quickly drawn test jelly g.",
        "author": "Vex",
        "date": "29 Apr 2025 19:25:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "ghost.png",
        "title": "Jelly G. meets a ghost",
        "author": "Vex",
        "date": "04 May 2025 17:33:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "ghost2.png",
        "title": "The ghost causes mayhem",
        "author": "Vex",
        "date": "04 May 2025 17:52:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "ghost3.png",
        "title": "Jelly G. asks Fimble for help",
        "author": "Vex",
        "date": "06 May 2025 03:17:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "ghost4.png",
        "title": "Communicating with the ghost",
        "author": "Vex",
        "date": "06 May 2025 03:35:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "borp2.png",
        "title": "Jelly G. on BORP disease",
        "author": "Vex",
        "date": "06 May 2025 04:00:00 GMT+1",
        "comment": "",
    },
	{
		"filename": "packageg.png",
		"title": "Jelly G. on a box!",
		"author": "Ardent",
		"date": "09 May 2025 22:23:00 GMT+1",
		"comment": "",
	},
    {
        "filename": "razor.png",
        "title": "really cool thing to wake up to",
        "author": "ocean",
        "date": "10 May 2025 16:33:00 GMT+1",
        "comment": "pro tip if you have a little brother amke sure he knows where your razor is so he can open the compartment over your desk and pour a months worth of shaved hair all over your desk and spread it out",
    },
    {
        "filename": "ghost5.png",
        "title": "Back in the present...",
        "author": "Vex",
        "date": "11 May 2025 03:22:00 GMT+1",
        "comment": "",
    },
	{
		"filename": "outage.png",
		"title": "Jelly G.allery down!?",
		"author": "Vex",
		"date": "13 May 2025 17:35:00 GMT+1",
		"comment": "",
	},
    {
        "filename": "sun.png",
        "title": "Jelly G. and the FREAKY ASS sun",
        "author": "Vex",
        "date": "17 May 2025 21:31:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "moon.png",
        "title": "The moon and the FREAKY ASS Jelly G.",
        "author": "fourplusfour",
        "date": "17 May 2025 22:05:00 GMT+1",
        "comment": "",
    },
	{
		"filename": "jellygodobadjawizardspell.png",
		"title": "#odobadja",
		"author": "kiooeht",
		"date": "19 May 2025 03:59:00 GMT+1",
		"comment": "",
    },
    {
        "filename": "odobadja2.png",
        "title": "Aftermath of the odobadja wizard spell",
        "author": "Vex",
        "date": "19 May 2025 04:50:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "odobadja3.png",
        "title": "The Caster mourns",
        "author": "Korbo",
        "date": "19 May 2025 05:08:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "tv.png",
        "title": "Jelly G. watches TV",
        "author": "Vex",
        "date": "02 Jun 2025 18:38:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "message.png",
        "title": "The Message",
        "author": "ocean",
        "date": "8 Jun 2025 18:00:00 GMT+1",
        "comment": "Some words in this strip might have a <a href='https://s.team/a/3301290'>deeper meaning</a>.",
    },
    {
        "filename": "audition1.png",
        "title": "The Audition, part 1",
        "author": "Vex",
        "date": "10 Jun 2025 21:30:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "audition2.png",
        "title": "The Audition, part 2",
        "author": "Vex",
        "date": "10 Jun 2025 22:02:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "stonebirthday1.png",
        "title": "Stone Fricking Thing's birthday",
        "author": "ocean",
        "date": "15 Jun 2025 23:28:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "stonebirthday2.png",
        "title": "And now, a word from our sponsor",
        "author": "ocean",
        "date": "15 Jun 2025 23:28:30 GMT+1",
        "comment": "",
    },
    {
        "filename": "stonebirthday3.png",
        "title": "Back at the Shop...",
        "author": "Vex",
        "date": "16 Jun 2025 05:25:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "stonebirthday4.png",
        "title": "Fimble helps Jelly G. track down Stone Fricking Thing",
        "author": "Vex",
        "date": "16 Jun 2025 05:25:30 GMT+1",
        "comment": "",
    },
    {
        "filename": "award.png",
        "title": "Jelly G. has an award for you",
        "author": "Vex",
        "date": "09 Jul 2025 05:10:00 GMT+1",
        "comment": "\"getting a bunch of ores so i can get armor so i can beat a boss so i can get more ores... that's some of the best games right there\"",
    },
    {
        "filename": "apology.png",
        "title": "Jelly G. and the apology potion",
        "author": "Vex",
        "date": "13 Jul 2025 01:11:00 GMT+1",
        "comment": "use this for when you have made a mistake and you need to say \"sorry\" (he has to drink it because of what you did)",
    },
    {
        "filename": "hammer.png",
        "title": "Jelly G. gets hammered",
        "author": "ocean",
        "date": "20 Jul 2025 17:00:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "toilet.png",
        "title": "Mr. Toilet says hi",
        "author": "Vex & Enbeon",
        "date": "27 Jul 2025 22:33:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "toiletboss.png",
        "title": "Mr. Toilet boss fight",
        "author": "Vex & Enbeon",
        "date": "27 Jul 2025 22:38:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "bite.png",
        "title": "The Bite of 'G.",
        "author": "ocean",
        "date": "29 Jul 2025 15:34:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "finger.png",
        "title": "The finger",
        "author": "ocean",
        "date": "29 Jul 2025 15:45:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "context.png",
        "title": "Context",
        "author": "Vex",
        "date": "07 Aug 2025 03:44:00 GMT+1",
    },
    {
        "filename": "jellybeans.png",
        "title": "Jelly Beans",
        "author": "Vex",
        "date": "07 Aug 2025 03:52:00 GMT+1",
    },
    {
        "filename": "sorryforswearing.png",
        "title": "Sorry for Swearing",
        "author": "Vex",
        "date": "07 Aug 2025 03:54:00 GMT+1",
    },
    {
        "filename": "fall.png",
        "title": "\"How people fall for this is beyond me\"",
        "author": "ocean",
        "date": "10 Aug 2025 15:52:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "powercard.png",
        "title": "\"that's a neat relic, would be fun as a power card too in the right context'\"",
        "author": "Lua Viper",
        "date": "24 Aug 2025 18:47:00 GMT+1",
        "comment": "Featuring the professor from <a href='https://steamcommunity.com/sharedfiles/filedetails/?id=3410083760'>Spire Cafe</a>.",
    },
    {
        "filename": "singingG.mp4",
        "videoType": "mp4",
        "thumb": "singingG-thumb.png",
        "title": "SINGING G.",
        "author": "ocean",
        "date": "26 Aug 2025 22:25:00 GMT+1",
        "comment": "this is a parody of my favourite youtube video ever, <a href='https://youtu.be/U2suj6q_gME?list=PLBGRrWbJlzNwqg_hM_Z_9SDFqF2OptWIm'>SINGING COWS</a>",
    },
    {
        "filename": "smaller.png",
        "title": "Smaller",
        "author": "Vex",
        "date": "26 Aug 2025 22:44:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "sizes.png",
        "title": "The various sizes of G.",
        "author": "Dayvig",
        "date": "26 Aug 2025 23:00:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "retro.png",
        "title": "Retro G.",
        "author": "Vex",
        "date": "30 Aug 2025 6:47:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "wah.png",
        "title": "Arch-rivals",
        "author": "Lua Viper",
        "date": "30 Aug 2025 21:45:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "elon.png",
        "title": "Space X.",
        "author": "Lua Viper",
        "date": "30 Aug 2025 23:16:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "jellyg.png",
        "title": "Jelly G. on... himself?",
        "author": "Vex",
        "date": "01 Sep 2025 18:09:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "sharpe.png",
        "title": "What if Sharpe met Jelly G.!?",
        "author": "Vex",
        "date": "01 Sep 2025 18:17:00 GMT+1",
        "comment": "crazy crossover: this lost concept art now released",
    },
    {
        "filename": "engineering.png",
        "title": "Engineering design",
        "author": "Lua Viper",
        "date": "24 Sep 2025 23:48:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "desk.png",
        "title": "Desk",
        "author": "Vex",
        "date": "25 Sep 2025 19:33:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "pregnantjellyg.png",
        "title": "pregnantjellyg.png",
        "author": "anon",
        "date": "28 Sep 2025 15:00:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "content.png",
        "title": "\"if anything the jelly g. content rate has risen lately\"",
        "author": "Vex",
        "date": "28 Sep 2025 22:04:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "orange.png",
        "title": "words collide",
        "author": "ocean",
        "date": "29 Sep 2025 22:19:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "pyramid.png",
        "title": "Food Pyramid",
        "author": "ocean",
        "date": "08 Oct 2025 21:00:00 GMT+1",
        "comment": "i told ai to tell me the food pyramid it said \"im so glad you want to learn about this make sure to eat an equal amount of jelly g.'s, noxious fimbles and jelly h.'s\" i think its got a long way to go",
    },
    {
        "filename": "beans.png",
        "title": "Jelly B.eans",
        "author": "ocean",
        "date": "08 Oct 2025 21:05:00 GMT+1",
        "comment": "...cause obviously we figured out in 2008 that jelly h's and noxious fimbles are, nutritionally speaking, practically empty. these days your meals should be looking like this",
    },
    {
        "filename": "frosty.png",
        "title": "Frosty H.'s",
        "author": "ocean",
        "date": "08 Oct 2025 21:16:00 GMT+1",
        "comment": "of course those of us who do enjoy jelly h's for the taste are still free to indulge ourselves from time to time",
    },
    {
        "filename": "happyg.png",
        "title": "happy jelly g.",
        "author": "Vex",
        "date": "09 Oct 2025 22:05:00 GMT+1",
        "comment": "use this image when you're happy about something",
    },
    {
        "filename": "ipad.png",
        "title": "what if jelly g. got ipad",
        "author": "Vex",
        "date": "15 Oct 2025 02:13:00 GMT+1",
        "comment": "this is not my wholehearted support of apple i was just at the store incidentally",
    },
    {
        "filename": "bumps.png",
        "title": "apple jelly g.",
        "author": "ocean",
        "date": "15 Oct 2025 03:53:00 GMT+1",
        "comment": "\"apple jelly g. should only have a 1-bumped head instead of 2 bumps\"",
    },
    {
        "filename": "ascii.png",
        "title": "ascii g.",
        "author": "Vex",
        "date": "21 Oct 2025 05:37:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "dream.png",
        "title": "Jelly G. on dreams",
        "author": "Vex",
        "date": "22 Oct 2025 07:45:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "draw.png",
        "title": "Anyone can make Jelly G. comics!",
        "author": "Vex",
        "date": "22 Oct 2025 07:51:00 GMT+1",
        "comment": "That includes Jelly G.",
    },
    {
        "filename": "ironclad.png",
        "title": "Jelly G. dresses up for halloween",
        "author": "Aurora",
        "date": "22 Oct 2025 08:00:00 GMT+1",
        "comment": "",
    },
    {
        "filename": "whatthestonesay.mp4",
        "videoType": "mp4",
        "thumb": "whatthestonesay-thumb.png",
        "title": "WHAT DO YOU SAY?",
        "author": "ocean",
        "date": "31 Oct 2025 17:57:00 GMT",
        "comment": "See also: <a href=https://www.tiktok.com/@ragefaic/video/7091702668955012358>this TikTok</a>",
    },
    {
        "filename": "gellyjexplains.png",
        "title": "Gelly J. explains",
        "author": "Enbeon",
        "date": "10 Nov 2025 00:45:00 GMT",
        "comment": "",
    },
    {
        "filename": "movie.png",
        "title": "Jelly G.: The Movie",
        "author": "Vex",
        "date": "16 Nov 2025 18:51:00 GMT",
        "comment": "",
    },
    {
        "filename": "fightinggame.png",
        "title": "Jelly G. VS Jelly H.",
        "author": "Vex",
        "date": "22 Nov 2025 20:31:00 GMT",
        "comment": "\"i love when fighting games have a story mode and becuase they need to use all the characters or whatever it's like\"",
    },
    {
        "filename": "dialogue.png",
        "title": "Pre-fight dialogue",
        "author": "Vex",
        "date": "22 Nov 2025 22:00:00 GMT",
        "comment": "\"also when they have to write pre-fight dialogue for every set of characters even when the characters are friends who would never fight\"",
    },
    {
        "filename": "tellyv.png",
        "title": "Telly V.",
        "author": "ocean",
        "date": "28 Nov 2025 01:07:00 GMT",
        "comment": "",
    },
    {
        "filename": "skellyt.png",
        "title": "Skelly T.",
        "author": "ocean",
        "date": "28 Nov 2025 01:07:00 GMT",
        "comment": "",
    },
    {
        "filename": "shellyc.png",
        "title": "Shelly C.",
        "author": "ocean",
        "date": "28 Nov 2025 01:07:00 GMT",
        "comment": "",
    },
    {
        "filename": "smellyp.png",
        "title": "Smelly P.",
        "author": "ocean",
        "date": "28 Nov 2025 01:07:00 GMT",
        "comment": "",
    },
    {
        "filename": "interference.png",
        "title": "Telly V. on interference",
        "author": "Vex",
        "date": "28 Nov 2025 03:16:00 GMT",
        "comment": "",
    },
    {
        "filename": "skeleton.png",
        "title": "Skelly T. on 💀",
        "author": "Vex",
        "date": "28 Nov 2025 03:32:00 GMT",
        "comment": "",
    },
    {
        "filename": "beach.png",
        "title": "Shelly C. on the beach",
        "author": "Vex",
        "date": "28 Nov 2025 03:47:00 GMT",
        "comment": "",
    },
    {
        "filename": "smellyp2.png",
        "title": "Say the line, Smelly P.!",
        "author": "Vex",
        "date": "28 Nov 2025 03:48:00 GMT",
        "comment": "",
    },
    {
        "filename": "anvil.png",
        "title": "Jell-yeouch G.",
        "author": "Aurora",
        "date": "28 Nov 2025 04:42:00 GMT",
        "comment": "",
    },
    {
        "filename": "television.png",
        "title": "\"i love Television i wish i was on the Teleiviosn\"",
        "author": "ocean",
        "date": "29 Nov 2025 05:15:00 GMT",
        "comment": "",
    },
    {
        "filename": "smellyp3.png",
        "title": "But where's Smelly P.?",
        "author": "Vex",
        "date": "29 Nov 2025 06:01:00 GMT",
        "comment": "",
    },
    {
        "filename": "pebble.png",
        "title": "The gang apologise to Smelly P.",
        "author": "Vex",
        "date": "29 Nov 2025 06:41:00 GMT",
        "comment": "",
    },
    {
        "filename": "prank.png",
        "title": "Just a prank bro",
        "author": "ocean",
        "date": "29 Nov 2025 07:05:00 GMT",
        "comment": "",
    },
    {
        "filename": "maximum.png",
        "title": "And now: perhaps a hot take",
        "author": "Lua Viper",
        "date": "29 Nov 2025 07:42:00 GMT",
        "comment": "",
    },
    {
        "filename": "might.mp4",
        "videoType": "mp4",
        "thumb": "might-thumb.png",
        "title": "Two best friends",
        "author": "ocean",
        "date": "08 Dec 2025 23:48:00 GMT",
        "comment": "before you watch this i sincerely apologise in advance (<a href=https://www.tiktok.com/@kiwimangokittens/video/6974767132563213573>audio source</a>)",
    },
    {
        "filename": "babies.png",
        "title": "Jelly babies",
        "author": "ocean",
        "date": "08 Dec 2025 23:58:00 GMT",
        "comment": "",
    },
    {
        "filename": "reaction.png",
        "title": "Fimble's reaction to that information",
        "author": "Vex",
        "date": "09 Dec 2025 00:08:00 GMT",
        "comment": "",
    },
    {
        "filename": "birthday2.png",
        "title": "Jelly G. wishes you a happy birthday",
        "author": "Vex",
        "date": "16 Dec 2025 23:31:00 GMT",
        "comment": "",
    },
    {
        "filename": "maximum2.png",
        "title": "Jelly G. on \"maximum\" again",
        "author": "Lua Viper",
        "date": "28 Dec 2025 05:16:00 GMT",
        "comment": "",
    },
    {
        "filename": "poyo.png",
        "title": "But how did Jelly G. learn game design?",
        "author": "Vex",
        "date": "28 Dec 2025 06:22:00 GMT",
        "comment": "",
    },
    {
        "filename": "jellygvsglip.ogg",
        "audioType": "ogg",
        "title": "Epic Rap Battle: Jelly G. VS Glip",
        "author": "Vex",
        "date": "31 Dec 2025 23:02:00 GMT",
        "comment": "",
    },
    {
        "filename": "build.gif",
        "thumb": "build-thumb.png",
        "title": "How to make a character",
        "author": "ocean",
        "date": "07 Jan 2026 16:25:00 GMT",
        "comment": "making a character is easy- oh shoot i made the same thing yet again goddammit",
    },
    {
        "filename": "portersmilejelly.png",
        "title": "Smile! :D",
        "author": "ocean",
        "date": "07 Jan 2026 16:41:00 GMT",
        "comment": "this would be jelly g characterts if they were the porter robisonson smile :D picture",
    },
    {
        "filename": "dizzy.gif",
        "thumb": "dizzy-thumb.png",
        "title": "Dizzy G.",
        "author": "Vex",
        "date": "08 Jan 2026 01:47:00 GMT",
        "comment": "",
    },
    {
        "filename": "trial.mp4",
        "videoType": "mp4",
        "thumb": "trial-thumb.png",
        "title": "The Trial",
        "author": "ocean",
        "date": "10 Jan 2026 22:47:00 GMT",
        "comment": "when jelly g's lawyer fell asleep in court why did they have to try and defend themself?? (<a href=https://youtu.be/Phh3oVCtzBg>audio source</a>)",
    },
]
